server:
  port: 8003

spring:
  application:
    name: micro-service-a
  cloud:
    consul:
      host: ${DS_SERVER:192.168.132.131}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${random.uuid}
#        hostname: 10.1.81.33
    config:
      profile: dev
      discovery:
        enabled: true             #开启服务发现，从注册中心找config-server服务
        service-id: config-server
    stream:
      bindings:
        hello_B:
          destination: sayHello
          content-type: application/json
          group: hello

  rabbitmq:
    host: 192.168.132.131
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always




