server:
  port: 7000

spring:
  application:
    name: zuul
  cloud:
    consul:
      host: ${DS_SERVER:192.168.132.131}
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${random.uuid}
        hostname: 10.1.81.33

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

zuul:
  routes:
    eureka-client-a:
      path: /service-a/**
      serviceId: eureka-client-a
    eureka-client-b:
      path: /service-b/**
      serviceId: micro-service-b
