server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/longlogn/config
          default-label: master
          search-paths: '{profile}'

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.81.33:8000/eureka/
